# Read the Docs configuration file for Zensical
# See https://docs.readthedocs.com/platform/stable/intro/zensical.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    # Install documentation dependencies only (not the full package)
    - pip install zensical
    # Build the documentation with Zensical
    - zensical build --site-dir $READTHEDOCS_OUTPUT/html
